services:
  database:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=property_api
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    expose:
      - 3306